### ISSUE TITLE
Arduino Nano Every

### ISSUE THREAD

**Issue by AlessandroAnnini** [silveirago/DIY-Midi-Controller#12]
I tried to define `ATMEGA328` as board but Nano every is actually a `ATMEGA4809`.
The real problem is that the board is not detected as midi by the system and I cannot use Hairless because my mac won't run it because it is outdated.

**Comment by silveirago** [comment]
Yeah, that should work with the Nano although it's not the the same chip, but you need Hairless. I just recommend using an Arduino Pro Micro instead.
