### ISSUE TITLE
Using ATmega328p chip

### ISSUE THREAD

**Issue by Pieterjan35** [silveirago/DIY-Midi-Controller#4]
Hey! 

Quick question, I Found a Arduino mega I want to use. But it uses an ATmega328p chip. Can I just change the definition of the Board to ATmega328p or will the code not work? 

Define your board, choose:
// "ATMEGA328" if using ATmega328

**Comment by silveirago** [comment]
“ATMEGA328” definition Will work with Mega.

Gustavo Silveira
