### ISSUE TITLE
midi not declared

### ISSUE THREAD

**Issue by Birbpal** [silveirago/DIY-Midi-Controller#7]
i tried restarting, i have everything installed i have no idea why it doesnt work

**Comment by dido2999** [comment]
I think that you should uncomment the MIDI_CREATE_DEFAULT_INSTANCE(); declaration at row 36.

**Comment by dido2999** [comment]
I think that you should uncomment the MIDI_CREATE_DEFAULT_INSTANCE(); declaration at row 36.

> i tried restarting, i have everything installed i have no idea why it doesnt work

**Comment by Birbpal** [comment]
omg thank you so much your a life saver
